# Generated by Django 5.2.16 on 2026-07-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='stock_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='stock_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
