# Generated by Django 5.2.16 on 2026-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bill_delivery_charge_bill_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_walk_in_account',
            field=models.BooleanField(default=False),
        ),
    ]
