# Generated by Django 5.2.16 on 2026-07-17 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bill_payment_type_partial_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillEditAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_audits', to='core.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_edit_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edit_date', '-id'],
            },
        ),
    ]
