# Generated by Django 5.2.16 on 2026-07-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_referencecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('credit', 'Credit (+)'), ('debit', 'Debit (-)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=500)),
                ('adjustment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to='core.customer')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
    ]
