# Generated by Django 5.2.16 on 2026-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customerbalanceadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
