# Generated by Django 5.2.16 on 2026-07-18 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_payment_customer_alter_payment_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(max_length=500)),
                ('stock_before', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='core.product')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
    ]
