# Generated by Django 5.2.16 on 2026-07-18 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyOtherWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(unique=True)),
                ('driver', models.CharField(blank=True, max_length=500)),
                ('material_supply', models.CharField(blank=True, max_length=500)),
                ('material_mixing', models.CharField(blank=True, max_length=500)),
                ('other', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edit_reason', models.CharField(blank=True, max_length=500)),
                ('edit_date', models.DateField(blank=True, null=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_other_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMachineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('not_working', 'Not working')], default='running', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_machine_runs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_runs', to='core.product')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_runs', to='core.machine')),
            ],
            options={
                'ordering': ['-run_date', 'machine__name'],
                'unique_together': {('run_date', 'machine')},
            },
        ),
    ]
