# Generated by Django 5.2.16 on 2026-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customer_email_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Senovka Plastics', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Plastic Manufacturing', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('phone_alt', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('business_reg_no', models.CharField(blank=True, default='', max_length=100)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=60)),
                ('footer_note', models.CharField(blank=True, default='Thank you for your business.', max_length=300)),
                ('terms_line', models.CharField(blank=True, default='', max_length=300)),
                ('show_watermark', models.BooleanField(default=True)),
                ('watermark_text', models.CharField(blank=True, default='SENOVKA', help_text='Text drawn diagonally in a very faint colour behind the bill. Leave blank to use the logo image instead.', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing settings',
                'verbose_name_plural': 'Billing settings',
            },
        ),
    ]
