# Generated by Django 5.2.16 on 2026-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_billingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
