# Generated by Django 5.2.16 on 2026-08-20 05:12

from django.db import migrations, models


def copy_existing_numbers(apps, schema_editor):
    Bill = apps.get_model("core", "Bill")
    for bill in Bill.objects.filter(bill_number__isnull=True).only("pk").iterator():
        Bill.objects.filter(pk=bill.pk).update(bill_number=bill.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customer_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(copy_existing_numbers, migrations.RunPython.noop),
    ]
