# Generated by Django 5.2.17 on 2026-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_chequereceiveddateeditaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="bounced_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
