# Generated by Django 5.2.17 on 2026-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_cheque_bounced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheque",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("deposited", "Deposited"),
                    ("bounced", "Returned"),
                    ("held", "Held"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
