# Generated by Django 5.2.17 on 2026-09-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_bill_rounding_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashdrawer",
            name="supplier_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_drawer_entries",
                to="core.supplierbill",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="supplier_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cheques",
                to="core.supplierbill",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="supplier_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.supplierbill",
            ),
        ),
    ]
