# Generated by Django 5.2.17 on 2026-09-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_supplier_bill_payment_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("confirmed", "Confirmed"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
