# Generated by Django 6.1.1 on 2026-09-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_vehicletrip_start_km_end_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='OversaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('oversale_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oversale_records', to='core.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oversale_records', to='core.product')),
            ],
            options={
                'ordering': ['-oversale_date', '-id'],
            },
        ),
    ]
