# Generated by Django 6.1.1 on 2026-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_oversale_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='last_bill_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='last_supplier_bill_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
