# Generated by Django 6.1.1 on 2026-09-28 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_stockadjustment_watermarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('return_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='core.customer')),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('wrong_item', 'Wrong item supplied'), ('excess', 'Excess quantity'), ('not_required', 'No longer required'), ('quality', 'Quality complaint'), ('other', 'Other')], max_length=20)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('restocked', models.BooleanField(default=False)),
                ('stock_before', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.customerreturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='core.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
