# Generated by Django 6.1.1 on 2026-09-28 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_customer_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='billeditaudit',
            name='new_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billeditaudit',
            name='previous_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='SupplierBillEditAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateField()),
                ('previous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_bill_edit_audits', to=settings.AUTH_USER_MODEL)),
                ('supplier_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_audits', to='core.supplierbill')),
            ],
            options={
                'ordering': ['-edit_date', '-id'],
            },
        ),
    ]
